CREATE DATABASE ATIMO

USE ATIMO

CREATE TABLE PROJETO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NUM_DOC VARCHAR(18),
	DESCRICAO VARCHAR(200) NOT NULL,
	FLG_RATEIO CHAR(1) NOT NULL DEFAULT 'N', /* N - NÃO / S - SIM */
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

INSERT INTO PROJETO (DESCRICAO, FLG_RATEIO, SITUACAO) VALUES ('MANUTENÇÃO', 'S', 'A')
INSERT INTO PROJETO (DESCRICAO, FLG_RATEIO, SITUACAO) VALUES ('OBRAS', 'S', 'A')

CREATE TABLE DEPARTAMENTO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE FUNCAO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(200)
)

CREATE TABLE PESSOA(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TIPO CHAR(1) NOT NULL DEFAULT 'C', /* C - CLIENTE / F - FORNECEDOR / U - FUNCIONARIO / T - TERCEIRO */
	TIPO_DOC CHAR(1) NOT NULL DEFAULT 'J', /* F - PESSOA FISICA / J - PESSOA JURIDICA */
	NUM_DOC VARCHAR(18) NOT NULL,
	INSC_ESTADUAL VARCHAR(50),
	RAZAO VARCHAR(200) NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	COMPLEMENTO TEXT,
	BAIRRO VARCHAR(200) NOT NULL,
	CIDADE VARCHAR(200) NOT NULL,
	UF CHAR(2) NOT NULL,
	ZONA VARCHAR(50),
	TELEFONE1 VARCHAR(15),
	TELEFONE2 VARCHAR(15),
	TELEFONE3 VARCHAR(15),
	CONTATO VARCHAR(50),
	EMAIL VARCHAR(200) NOT NULL,
	OBSERVACAO TEXT,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE BENEFICIO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	FORNECEDOR INT NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	CUMULATIVO CHAR(1) NOT NULL DEFAULT 'N', /* N - NÃO / S - SIM */
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE BENEFICIO ADD CONSTRAINT FK_BENEFICIO_FORNECEDOR FOREIGN KEY (FORNECEDOR) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE FERIADO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	DATA VARCHAR(5) NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL
)

CREATE TABLE FORMA_PAGAMENTO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE BANCO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CODIGO CHAR(6) NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE COMO_CONHECEU(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE UNIDADE(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(200) NOT NULL,
	SIGLA CHAR(5) NOT NULL
)

CREATE TABLE ESPECIALIDADE(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE GRUPO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TIPO CHAR(1) NOT NULL DEFAULT 'E', /* E - EQUIPAMENTO / F - FERRAMENTA / M - MATERIAL */
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE TIPO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TIPO CHAR(1) NOT NULL DEFAULT 'E', /* E - EQUIPAMENTO / F - FERRAMENTA / M - MATERIAL */
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE MARCA(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TIPO CHAR(1) NOT NULL DEFAULT 'E', /* E - EQUIPAMENTO / V - VEICULO */
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE MODELO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TIPO CHAR(1) NOT NULL DEFAULT 'E', /* E - EQUIPAMENTO / V - VEICULO */
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

CREATE TABLE SERVICO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	ESPECIALIDADE INT NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES ESPECIALIDADE (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE MATERIAL(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	GRUPO INT NOT NULL,
	TIPO INT NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	OBSERVACAO TEXT
)

ALTER TABLE MATERIAL ADD CONSTRAINT FK_MATERIAL_GRUPO FOREIGN KEY (GRUPO) REFERENCES GRUPO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE MATERIAL ADD CONSTRAINT FK_MATERIAL_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE FERRAMENTA(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	GRUPO INT NOT NULL,
	TIPO INT NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	MINIMO INT NOT NULL DEFAULT 0,
	OBSERVACAO TEXT,
	FLG_CONSUMIVEL CHAR(1) NOT NULL DEFAULT 'N' /* N - NÃO / S - SIM */
)

ALTER TABLE FERRAMENTA ADD CONSTRAINT FK_FERRAMENTA_GRUPO FOREIGN KEY (GRUPO) REFERENCES GRUPO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE FERRAMENTA ADD CONSTRAINT FK_FERRAMENTA_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE EQUIPAMENTO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	GRUPO INT NOT NULL,
	TIPO INT NOT NULL,
	MARCA INT,
	MODELO INT,
	DESCRICAO VARCHAR(200) NOT NULL,
	FABRICANTE VARCHAR(200),
	NUM_SERIE VARCHAR(50) NOT NULL,
	OBSERVACAO TEXT,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE EQUIPAMENTO ADD CONSTRAINT FK_EQUIPAMENTO_GRUPO FOREIGN KEY (GRUPO) REFERENCES GRUPO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE EQUIPAMENTO ADD CONSTRAINT FK_EQUIPAMENTO_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE EQUIPAMENTO ADD CONSTRAINT FK_EQUIPAMENTO_MARCA FOREIGN KEY (MARCA) REFERENCES MARCA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE EQUIPAMENTO ADD CONSTRAINT FK_EQUIPAMENTO_MODELO FOREIGN KEY (MODELO) REFERENCES MODELO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE VEICULO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	MARCA INT,
	MODELO INT,
	ANO INT NOT NULL,
	CHASSI VARCHAR(50),
	PLACA VARCHAR(8) NOT NULL,
	COMBUSTIVEL CHAR(1) NOT NULL DEFAULT 'G', /* A - ALCOOL / F - FLEX / G - GASOLINA */
	SEGURO DECIMAL(15,2) NOT NULL DEFAULT 0,
	IPVA DECIMAL(15,2) NOT NULL DEFAULT 0,
	OBSERVACAO TEXT,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_MARCA FOREIGN KEY (MARCA) REFERENCES MARCA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_MODELO FOREIGN KEY (MODELO) REFERENCES MODELO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE PATRIMONIO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NUMERO VARCHAR(50) NOT NULL,
	FLG_DEPRECIA CHAR(1) NOT NULL DEFAULT 'N', /* N - NÃO / S - SIM */
	DATA_AQUISICAO DATE NOT NULL,
	VALOR_COMPRA DECIMAL(15,2) NOT NULL DEFAULT 0,
	TIPO_DEPRECIACAO CHAR(1) NOT NULL DEFAULT 'A', /* A - ANUAL / M - MENSAL / S - SEMESTRAL / N - NENHUMA */
	DEPRECIACAO DECIMAL(15,2) NOT NULL DEFAULT 0,
	FERRAMENTA INT,
	VEICULO INT,
	EQUIPAMENTO INT
)

ALTER TABLE PATRIMONIO ADD CONSTRAINT FK_PATRIMONIO_FERRAMENTA FOREIGN KEY (FERRAMENTA) REFERENCES FERRAMENTA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE PATRIMONIO ADD CONSTRAINT FK_PATRIMONIO_VEICULO FOREIGN KEY (VEICULO) REFERENCES VEICULO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE PATRIMONIO ADD CONSTRAINT FK_PATRIMONIO_EQUIPAMENTO FOREIGN KEY (EQUIPAMENTO) REFERENCES EQUIPAMENTO (ID)

CREATE TABLE RATEIO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	PROJETO INT NOT NULL,
	FERRAMENTA INT,
	DEPARTAMENTO INT,
	VEICULO INT,
	EQUIPAMENTO INT,
	PESSOA INT,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE RATEIO ADD CONSTRAINT FK_RATEIO_PROJETO FOREIGN KEY (PROJETO) REFERENCES PROJETO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE RATEIO ADD CONSTRAINT FK_RATEIO_FERRAMENTA FOREIGN KEY (FERRAMENTA) REFERENCES FERRAMENTA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE RATEIO ADD CONSTRAINT FK_RATEIO_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE RATEIO ADD CONSTRAINT FK_RATEIO_VEICULO FOREIGN KEY (VEICULO) REFERENCES VEICULO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE RATEIO ADD CONSTRAINT FK_RATEIO_EQUIPAMENTO FOREIGN KEY (EQUIPAMENTO) REFERENCES EQUIPAMENTO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE RATEIO ADD CONSTRAINT FK_RATEIO_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE ANEXO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(200) NOT NULL,
	TIPO CHAR(5) NOT NULL,
	ANEXO VARBINARY(MAX) NOT NULL
)

CREATE TABLE FORNECEDOR_TIPO_MATERIAL(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	FORNECEDOR INT NOT NULL,
	TIPO INT NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE FORNECEDOR_TIPO_MATERIAL ADD CONSTRAINT FK_FORNECEDOR_TIPO_MATERIAL_FORNECEDOR FOREIGN KEY (FORNECEDOR) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE FORNECEDOR_TIPO_MATERIAL ADD CONSTRAINT FK_FORNECEDOR_TIPO_MATERIAL_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE TERCEIRO_SERVICO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TERCEIRO INT NOT NULL,
	SERVICO INT NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE TERCEIRO_SERVICO ADD CONSTRAINT FK_TERCEIRO_SERVICO_TERCEIRO FOREIGN KEY (TERCEIRO) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE TERCEIRO_SERVICO ADD CONSTRAINT FK_TERCEIRO_SERVICO_SERVICO FOREIGN KEY (SERVICO) REFERENCES SERVICO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE PESSOA_BENEFICIO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	PESSOA INT NOT NULL,
	BENEFICIO INT NOT NULL,
	TIPO_DEDUCAO CHAR(1) NOT NULL DEFAULT 'V', /* P - PERCENTUAL / V - VALOR */
	DEDUCAO DECIMAL(15,2) NOT NULL DEFAULT 0,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE PESSOA_BENEFICIO ADD CONSTRAINT FK_PESSOA_BENEFICIO_PESSOA FOREIGN KEY (PESSOA) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE PESSOA_BENEFICIO ADD CONSTRAINT FK_PESSOA_BENEFICIO_BENEFICIO FOREIGN KEY (BENEFICIO) REFERENCES BENEFICIO (ID) 

CREATE TABLE PESSOA_FUNCIONARIO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	FUNCIONARIO INT NOT NULL,
	FUNCAO INT NOT NULL,
	DATA_ADMISSAO DATE NOT NULL,
	DATA_DEMISSAO DATE,
	SALARIO DECIMAL(15,2) NOT NULL DEFAULT 0
)

ALTER TABLE PESSOA_FUNCIONARIO ADD CONSTRAINT FK_PESSOA_FUNCIONARIO_PESSOA FOREIGN KEY (FUNCIONARIO) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE PESSOA_FUNCIONARIO ADD CONSTRAINT FK_PESSOA_FUNCIONARIO_FUNCAO FOREIGN KEY (FUNCAO) REFERENCES FUNCAO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE FUNCIONARIO_DEPARTAMENTO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	FUNCIONARIO INT NOT NULL,
	DEPARTAMENTO INT NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE FUNCIONARIO_DEPARTAMENTO ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO_FUNCIONARIO FOREIGN KEY (FUNCIONARIO) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE FUNCIONARIO_DEPARTAMENTO ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE FUNCIONARIO_CHECK_LIST(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	FUNCIONARIO INT NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	ANEXO INT,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE FUNCIONARIO_CHECK_LIST ADD CONSTRAINT FK_FUNCIONARIO_CHECK_LIST_FUNCIONARIO FOREIGN KEY (FUNCIONARIO) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE FUNCIONARIO_CHECK_LIST ADD CONSTRAINT FK_FUNCIONARIO_CHECK_LIST_ANEXO FOREIGN KEY (ANEXO) REFERENCES ANEXO (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE PESSOA_CLIENTE(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CLIENTE INT NOT NULL,
	FLG_LOJA CHAR(1) NOT NULL DEFAULT 'N', /* N - NÃO / S - SIM */
	FLG_CONTRATO CHAR(1) NOT NULL DEFAULT 'N' /* N - NÃO / S - SIM */
)

ALTER TABLE PESSOA_CLIENTE ADD CONSTRAINT FK_PESSOA_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES PESSOA (ID) ON UPDATE  CASCADE ON DELETE CASCADE

CREATE TABLE CLIENTE_COMO_CONHECEU(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CLIENTE INT NOT NULL,
	COMO_CONHECEU INT NOT NULL,
	OUTROS VARCHAR(100)
)

ALTER TABLE CLIENTE_COMO_CONHECEU ADD CONSTRAINT FK_CLIENTE_COMO_CONHECEU_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE CLIENTE_COMO_CONHECEU ADD CONSTRAINT FK_CLIENTE_COMO_CONHECEU_COMO_CONHECEU FOREIGN KEY (COMO_CONHECEU) REFERENCES COMO_CONHECEU (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE LOJA(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CLIENTE INT NOT NULL,
	NUM_DOC VARCHAR(18) NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	COMPLEMENTO TEXT,
	BAIRRO VARCHAR(200) NOT NULL,
	CIDADE VARCHAR(200) NOT NULL,
	UF CHAR(2) NOT NULL,
	ZONA VARCHAR(50),
	TELEFONE1 VARCHAR(15),
	TELEFONE2 VARCHAR(15),
	TELEFONE3 VARCHAR(15),
	CONTATO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	OBSERVACAO TEXT,
	FATURAR_EM CHAR(1) NOT NULL DEFAULT 'C', /* C - CLIENTE / L - LOJA */
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE LOJA ADD CONSTRAINT FK_LOJA_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE CONTRATO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CLIENTE INT NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	DURACAO INT NOT NULL DEFAULT 0,
	PERIODICIDADE INT NOT NULL DEFAULT 0,
	FLG_CORTESIA CHAR(1) NOT NULL DEFAULT 'N', /* N - NÃO / S - SIM */
	QTD_CORTESIA INT NOT NULL DEFAULT 0,
	FLG_EXTRA CHAR(1) NOT NULL DEFAULT 'N', /* N - NÃO / S - SIM */
	VALOR_EXTRA DECIMAL(15,2) NOT NULL DEFAULT 0
)

ALTER TABLE CONTRATO ADD CONSTRAINT FK_CONTRATO_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE CONTRATO_ESPECIALIDADE(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CONTRATO INT NOT NULL,
	ESPECIALIDADE INT NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE CONTRATO_ESPECIALIDADE ADD CONSTRAINT FK_CONTRATO_ESPECIALIDADE_CONTRATO FOREIGN KEY (CONTRATO) REFERENCES CONTRATO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE CONTRATO_ESPECIALIDADE ADD CONSTRAINT FK_CONTRATO_ESPECIALIDADE_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES ESPECIALIDADE (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE CONTRATO_LOJA(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CONTRATO INT NOT NULL,
	LOJA INT NOT NULL,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE CONTRATO_LOJA ADD CONSTRAINT FK_CONTRATO_LOJA_CONTRATO FOREIGN KEY (CONTRATO) REFERENCES CONTRATO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE CONTRATO_LOJA ADD CONSTRAINT FK_CONTRATO_LOJA_LOJA FOREIGN KEY (LOJA) REFERENCES LOJA (ID)

CREATE TABLE CONTRATO_SERVICO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	CONTRATO INT NOT NULL,
	SERVICO VARCHAR(200) NOT NULL,
	UNIDADE INT NOT NULL,
	TERCEIRO INT NOT NULL,
	QUANTIDADE DECIMAL(15,2) NOT NULL DEFAULT 0,
	VALOR_MO DECIMAL(15,2) NOT NULL DEFAULT 0,
	VALOR_MAT DECIMAL(15,2) NOT NULL DEFAULT 0,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'A' /* A - ATIVO / I - INATIVO */
)

ALTER TABLE CONTRATO_SERVICO ADD CONSTRAINT FK_CONTRATO_SERVICO_CONTRATO FOREIGN KEY (CONTRATO) REFERENCES CONTRATO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE CONTRATO_SERVICO ADD CONSTRAINT FK_CONTRATO_SERVICO_UNIDADE FOREIGN KEY (UNIDADE) REFERENCES UNIDADE (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE CONTRATO_SERVICO ADD CONSTRAINT FK_CONTRATO_SERVICO_TERCEIRO FOREIGN KEY (TERCEIRO) REFERENCES PESSOA (ID)

CREATE TABLE OSSB(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	TIPO_RESPONSAVEL CHAR(1) DEFAULT 'U', /* U - EQUIPE PRÓPRIA / T - TERCEIRO */
	RESPONSAVEL INT,
	TIPO_SUPERVISOR CHAR(1) DEFAULT 'U', /* U - EQUIPE PRÓPRIA / T - TERCEIRO */
	SUPERVISOR INT,
	CONTRATO INT,
	DATA_CADASTRO DATE NOT NULL,
	PROJETO INT NOT NULL,
	CLIENTE INT NOT NULL,
	LOJA INT,
	OCORRENCIA TEXT NOT NULL,
	AGENDADO_DIA DATE,
	VISITADO_DIA DATE,
	PORTE CHAR(1) NOT NULL DEFAULT 'G', /* P - PEQUENO / M - MEDIO / G -GRANDE */
	AMBIENTE CHAR(1) NOT NULL DEFAULT 'A', /* A - AMBOS / E - EXTERNO / I - INTERNO */
	TIPO CHAR(1) NOT NULL DEFAULT 'P', /* P - PREVENTIVA / C - CORRETIVA / E - EMERGENCIAL / X - EXTRA COM CUSTO / S - EXTRA SEM CUSTO */
	SITUACAO CHAR(1) NOT NULL DEFAULT 'I', /* I - VISITA INICIAL / O - ORÇAR / R - ORÇAMENTO / E - EXECUTANDO / P - PARCELAMENTO / B - COBRANÇA / F - FINALIZADA / C - CANCELADA */
	EXECUCAO_INICIO DATE,
	EXECUCAO_FIM DATE,
	PREVISAO_INICIO DATE,
	PREVISAO_FIM DATE,
	EFETIVO_INICIO DATE,
	EFETIVO_FIM DATE,
	OBSERVACAO TEXT
)

ALTER TABLE OSSB ADD CONSTRAINT FK_OSSB_RESPONSAVEL FOREIGN KEY (RESPONSAVEL) REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB ADD CONSTRAINT FK_OSSB_SUPERVISOR FOREIGN KEY (SUPERVISOR) REFERENCES PESSOA (ID)
ALTER TABLE OSSB ADD CONSTRAINT FK_OSSB_CONTRATO FOREIGN KEY (CONTRATO) REFERENCES CONTRATO (ID)
ALTER TABLE OSSB ADD CONSTRAINT FK_OSSB_PROJETO FOREIGN KEY (PROJETO)REFERENCES PROJETO (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB ADD CONSTRAINT FK_OSSB_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES PESSOA (ID)
ALTER TABLE OSSB ADD CONSTRAINT FK_OSSB_LOJA FOREIGN KEY (LOJA) REFERENCES LOJA (ID)

CREATE TABLE OSSB_COMUNICACAO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	OSSB INT NOT NULL,
	DATA DATE NOT NULL DEFAULT GETDATE(),
	TEXTO TEXT NOT NULL,
	FLG_INTERNO CHAR(1) NOT NULL DEFAULT 'N' /* N - NÃO / S - SIM */
)

ALTER TABLE OSSB_COMUNICACAO ADD CONSTRAINT FK_OSSB_COMUNICACAO_OSSB FOREIGN KEY (OSSB) REFERENCES OSSB (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE OSSB_ESPECIALIDADE(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	OSSB INT NOT NULL,
	ESPECIALIDADE INT NOT NULL
)

ALTER TABLE OSSB_ESPECIALIDADE ADD CONSTRAINT FK_OSSB_ESPECIALIDADE_OSSB FOREIGN KEY (OSSB) REFERENCES OSSB (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB_ESPECIALIDADE ADD CONSTRAINT FK_OSSB_ESPECIALIDADE_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES ESPECIALIDADE (ID) ON UPDATE CASCADE ON DELETE CASCADE

CREATE TABLE OSSB_SERVICO(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	OSSB INT NOT NULL,
	SERVICO VARCHAR(200) NOT NULL,
	UNIDADE INT NOT NULL,
	TERCEIRO INT NOT NULL,
	QUANTIDADE DECIMAL(15,2) NOT NULL DEFAULT 0,
	VALOR_MO DECIMAL(15,2) NOT NULL DEFAULT 0,
	VALOR_MAT DECIMAL(15,2) NOT NULL DEFAULT 0,
	FLG_ABANDONO CHAR(1) NOT NULL DEFAULT 'N', /* NÃO / S - SIM */
	VALOR_PAGO_ABANDONO DECIMAL(15,2) DEFAULT 0
)

ALTER TABLE OSSB_SERVICO ADD CONSTRAINT FK_OSSB_SERVICO_OSSB FOREIGN KEY (OSSB) REFERENCES OSSB (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB_SERVICO ADD CONSTRAINT FK_OSSB_SERVICO_UNIDADE FOREIGN KEY (UNIDADE) REFERENCES UNIDADE (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB_SERVICO ADD CONSTRAINT FK_OSSB_SERVICO_TERCEIRO FOREIGN KEY (TERCEIRO) REFERENCES PESSOA (ID)

CREATE TABLE OSSB_MATERIAL(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	OSSB INT NOT NULL,
	MATERIAL VARCHAR(200) NOT NULL,
	UNIDADE INT NOT NULL,
	FORNECEDOR INT,
	QUANTIDADE DECIMAL(15,2) NOT NULL DEFAULT 0,
	VALOR DECIMAL(15,2) NOT NULL DEFAULT 0,
	FLG_COBRAR CHAR(1) NOT NULL DEFAULT 'N' /* N - NÃO / S - SIM */
)

ALTER TABLE OSSB_MATERIAL ADD CONSTRAINT FK_OSSB_MATERIAL_OSSB FOREIGN KEY (OSSB) REFERENCES OSSB (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB_MATERIAL ADD CONSTRAINT FK_OSSB_MATERIAL_UNIDADE FOREIGN KEY (UNIDADE) REFERENCES UNIDADE (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB_MATERIAL ADD CONSTRAINT FK_OSSB_MATERIAL_FORNECEDOR FOREIGN KEY (FORNECEDOR) REFERENCES PESSOA (ID)

CREATE TABLE OSSB_CHECK_LIST(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	OSSB INT NOT NULL,
	DESCRICAO VARCHAR(200) NOT NULL,
	ANEXO INT,
	SITUACAO CHAR(1) NOT NULL DEFAULT 'P' /* P - PENDENTE / E - ENTREGUE */
)

ALTER TABLE OSSB_CHECK_LIST ADD CONSTRAINT FK_OSSB_CHECK_LIST_OSSB FOREIGN KEY (OSSB) REFERENCES OSSB (ID) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE OSSB_CHECK_LIST ADD CONSTRAINT FK_OSSB_CHECK_LIST_ANEXO FOREIGN KEY (ANEXO) REFERENCES ANEXO (ID) ON UPDATE CASCADE ON DELETE CASCADE