//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA_MANUTENCAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AREA_MANUTENCAO()
        {
            this.CONTRATO_AREA_MANUTENCAO = new HashSet<CONTRATO_AREA_MANUTENCAO>();
            this.TERCEIRO_SERVICO = new HashSet<TERCEIRO_SERVICO>();
            this.CONTRATO_SERVICO = new HashSet<CONTRATO_SERVICO>();
        }
    
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
        public string SITUACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_AREA_MANUTENCAO> CONTRATO_AREA_MANUTENCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TERCEIRO_SERVICO> TERCEIRO_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_SERVICO> CONTRATO_SERVICO { get; set; }
    }
}
