//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAIXINHA
    {
        public int ID { get; set; }
        public System.DateTime DATA_ENTREGA { get; set; }
        public decimal VALOR { get; set; }
        public int PESSOA { get; set; }
        public int CONTA_BANCARIA { get; set; }
    
        public virtual PESSOA PESSOA1 { get; set; }
        public virtual CONTA_BANCARIA CONTA_BANCARIA1 { get; set; }
    }
}
