//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_SATISFACAO
    {
        public int POSTURA_EQUIPE { get; set; }
        public int CUMPRIMENTO_HORARIO { get; set; }
        public int SATISFACAO_SERVICO { get; set; }
        public string ASSINATURA { get; set; }
        public string COBRANCA { get; set; }
        public int MEDIA { get; set; }
        public int OSSB { get; set; }
    
        public virtual OSSB OSSB1 { get; set; }
    }
}
