//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_ITEM
    {
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
        public decimal VALOR { get; set; }
        public int UNIDADE { get; set; }
        public decimal QUANTIDADE { get; set; }
        public int COMPRA { get; set; }
    
        public virtual UNIDADE UNIDADE1 { get; set; }
        public virtual COMPRA COMPRA1 { get; set; }
    }
}
