//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO()
        {
            this.CONTRATO_ESPECIALIDADE = new HashSet<CONTRATO_ESPECIALIDADE>();
            this.CONTRATO_LOJA = new HashSet<CONTRATO_LOJA>();
            this.CONTRATO_SERVICO = new HashSet<CONTRATO_SERVICO>();
            this.OSSB = new HashSet<OSSB>();
            this.CONTRATO_AREA_MANUTENCAO = new HashSet<CONTRATO_AREA_MANUTENCAO>();
        }
    
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
        public string GERADO { get; set; }
        public int CLIENTE { get; set; }
        public string SITUACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_ESPECIALIDADE> CONTRATO_ESPECIALIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_LOJA> CONTRATO_LOJA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_SERVICO> CONTRATO_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB> OSSB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO_AREA_MANUTENCAO> CONTRATO_AREA_MANUTENCAO { get; set; }
    }
}
