//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTAS_RECEBER
    {
        public int ID { get; set; }
        public int OSSB { get; set; }
        public System.DateTime DATA_EMISSAO { get; set; }
        public System.DateTime DATA_VENCIMENTO { get; set; }
        public decimal VALOR_LIQUIDO { get; set; }
        public decimal VALOR_BRUTO { get; set; }
        public Nullable<System.DateTime> DATA_RECEBIMENTO { get; set; }
        public string NOTA_FISCAL { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> CONTA_BANCARIA { get; set; }
    
        public virtual OSSB OSSB1 { get; set; }
        public virtual CONTA_BANCARIA CONTA_BANCARIA1 { get; set; }
    }
}
