//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTAS_PAGAS
    {
        public long ID { get; set; }
        public Nullable<int> OSSB { get; set; }
        public Nullable<System.DateTime> DATA_PAGAMENTO { get; set; }
        public decimal VALOR { get; set; }
        public int DESPESA { get; set; }
        public int PESSOA { get; set; }
    
        public virtual DESPESA DESPESA1 { get; set; }
        public virtual PESSOA PESSOA1 { get; set; }
    }
}
