//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.FAT_FATURAMENTO = new HashSet<FAT_FATURAMENTO>();
            this.FAT_SERVICOS_PMSP = new HashSet<FAT_SERVICOS_PMSP>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string SERIAL_CERTIFICADO { get; set; }
        public string CNPJ { get; set; }
        public string COD_SERVICO_PMSP { get; set; }
        public string CCM_PMSP { get; set; }
        public string FLG_EMITE_NF { get; set; }
        public Nullable<int> NUM_ULTIMA_RPS { get; set; }
        public string FLG_OPTANTE_SIMPLES_NACIONAL { get; set; }
        public string NOM_FONTE_CARGA_TRIB { get; set; }
        public Nullable<decimal> PERC_CARGA_TRIB { get; set; }
        public string SERIE_RPS { get; set; }
        public Nullable<decimal> ALIQUOTA_ISS_FORA_MUNICIPIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_FATURAMENTO> FAT_FATURAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_SERVICOS_PMSP> FAT_SERVICOS_PMSP { get; set; }
    }
}
