//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMA_PAGAMENTO()
        {
            this.COMPRA_PARCELA = new HashSet<COMPRA_PARCELA>();
        }
    
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
        public string SITUACAO { get; set; }
        public int BANCO { get; set; }
        public string NUMERO_CONTA { get; set; }
        public string AGENCIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_PARCELA> COMPRA_PARCELA { get; set; }
    }
}
