//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR_TIPO_MATERIAL
    {
        public int ID { get; set; }
        public int FORNECEDOR { get; set; }
        public int TIPO { get; set; }
        public string SITUACAO { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
        public virtual TIPO TIPO1 { get; set; }
    }
}
