//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO_CARTAO_PONTO
    {
        public int ID { get; set; }
        public int FUNCIONARIO { get; set; }
        public System.DateTime MOMENTO { get; set; }
        public double LONGITUDE { get; set; }
        public double LATITUDE { get; set; }
        public string OBSERVACAO { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
    }
}
