//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO_DOCUMENTO
    {
        public int ID { get; set; }
        public int FUNCIONARIO { get; set; }
        public int ANEXO { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DATA_CRIACAO { get; set; }
        public string CATEGORIA { get; set; }
    
        public virtual ANEXO ANEXO1 { get; set; }
        public virtual PESSOA PESSOA { get; set; }
    }
}
