//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATIMOEntities : DbContext
    {
        public ATIMOEntities()
            : base("name=ATIMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANEXO> ANEXO { get; set; }
        public virtual DbSet<BANCO> BANCO { get; set; }
        public virtual DbSet<BENEFICIO> BENEFICIO { get; set; }
        public virtual DbSet<CLIENTE_COMO_CONHECEU> CLIENTE_COMO_CONHECEU { get; set; }
        public virtual DbSet<COMO_CONHECEU> COMO_CONHECEU { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<CONTRATO_ESPECIALIDADE> CONTRATO_ESPECIALIDADE { get; set; }
        public virtual DbSet<CONTRATO_LOJA> CONTRATO_LOJA { get; set; }
        public virtual DbSet<CONTRATO_SERVICO> CONTRATO_SERVICO { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<EQUIPAMENTO> EQUIPAMENTO { get; set; }
        public virtual DbSet<ESPECIALIDADE> ESPECIALIDADE { get; set; }
        public virtual DbSet<FERIADO> FERIADO { get; set; }
        public virtual DbSet<FERRAMENTA> FERRAMENTA { get; set; }
        public virtual DbSet<FORMA_PAGAMENTO> FORMA_PAGAMENTO { get; set; }
        public virtual DbSet<FORNECEDOR_TIPO_MATERIAL> FORNECEDOR_TIPO_MATERIAL { get; set; }
        public virtual DbSet<FUNCAO> FUNCAO { get; set; }
        public virtual DbSet<FUNCIONARIO_CHECK_LIST> FUNCIONARIO_CHECK_LIST { get; set; }
        public virtual DbSet<FUNCIONARIO_DEPARTAMENTO> FUNCIONARIO_DEPARTAMENTO { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<LOJA> LOJA { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MATERIAL> MATERIAL { get; set; }
        public virtual DbSet<MODELO> MODELO { get; set; }
        public virtual DbSet<OSSB> OSSB { get; set; }
        public virtual DbSet<OSSB_COMUNICACAO> OSSB_COMUNICACAO { get; set; }
        public virtual DbSet<OSSB_ESPECIALIDADE> OSSB_ESPECIALIDADE { get; set; }
        public virtual DbSet<OSSB_SERVICO> OSSB_SERVICO { get; set; }
        public virtual DbSet<PATRIMONIO> PATRIMONIO { get; set; }
        public virtual DbSet<PESSOA> PESSOA { get; set; }
        public virtual DbSet<PESSOA_CLIENTE> PESSOA_CLIENTE { get; set; }
        public virtual DbSet<PESSOA_FUNCIONARIO> PESSOA_FUNCIONARIO { get; set; }
        public virtual DbSet<PROJETO> PROJETO { get; set; }
        public virtual DbSet<RATEIO> RATEIO { get; set; }
        public virtual DbSet<SERVICO> SERVICO { get; set; }
        public virtual DbSet<TERCEIRO_SERVICO> TERCEIRO_SERVICO { get; set; }
        public virtual DbSet<TIPO> TIPO { get; set; }
        public virtual DbSet<UNIDADE> UNIDADE { get; set; }
        public virtual DbSet<VEICULO> VEICULO { get; set; }
        public virtual DbSet<AREA_MANUTENCAO> AREA_MANUTENCAOSet { get; set; }
        public virtual DbSet<CONTRATO_AREA_MANUTENCAO> CONTRATO_AREA_MANUTENCAO { get; set; }
        public virtual DbSet<DESPESA> DESPESA { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<OSSB_IMAGEM> OSSB_IMAGEM { get; set; }
        public virtual DbSet<COMPRA_PARCELA> COMPRA_PARCELA { get; set; }
        public virtual DbSet<TAREFA> TAREFAs { get; set; }
        public virtual DbSet<TAREFA_MEMBRO> TAREFA_MEMBRO { get; set; }
        public virtual DbSet<SUBTAREFA> SUBTAREFA { get; set; }
        public virtual DbSet<COMPRA_ITEM> COMPRA_ITEM { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<OSSB_SERVICO_TERCEIRO> OSSB_SERVICO_TERCEIRO { get; set; }
        public virtual DbSet<REGISTRO> REGISTRO { get; set; }
        public virtual DbSet<OSSB_ALBUM> OSSB_ALBUM { get; set; }
        public virtual DbSet<OSSB_CHECK_LIST> OSSB_CHECK_LIST { get; set; }
        public virtual DbSet<OSSB_TECNICO> OSSB_TECNICO { get; set; }
        public virtual DbSet<OSSB_VISTORIADOR> OSSB_VISTORIADOR { get; set; }
        public virtual DbSet<PAGAMENTO_TERCEIRO> PAGAMENTO_TERCEIRO { get; set; }
        public virtual DbSet<FAT_FATURAMENTO> FAT_FATURAMENTO { get; set; }
        public virtual DbSet<FAT_SERVICOS_PMSP> FAT_SERVICOS_PMSP { get; set; }
        public virtual DbSet<PAGAMENTO> PAGAMENTO { get; set; }
        public virtual DbSet<CAIXINHA> CAIXINHA { get; set; }
        public virtual DbSet<CAIXINHA_ITEM> CAIXINHA_ITEM { get; set; }
        public virtual DbSet<FUNCIONARIO_DOCUMENTO> FUNCIONARIO_DOCUMENTO { get; set; }
        public virtual DbSet<CONTAS_RECEBER> CONTAS_RECEBER { get; set; }
        public virtual DbSet<CONTAS_PAGAR> CONTAS_PAGAR { get; set; }
        public virtual DbSet<LOJA_EQUIPAMENTO> LOJA_EQUIPAMENTO { get; set; }
        public virtual DbSet<FUNCIONARIO_TIPO_ACESSO> FUNCIONARIO_TIPO_ACESSO { get; set; }
        public virtual DbSet<FUNCIONARIO_CARTAO_PONTO> FUNCIONARIO_CARTAO_PONTO { get; set; }
        public virtual DbSet<VEICULO_MULTA> VEICULO_MULTA { get; set; }
        public virtual DbSet<CONTAS_PAGAS> CONTAS_PAGAS { get; set; }
        public virtual DbSet<DESPESA_CLASSE> DESPESA_CLASSE { get; set; }
        public virtual DbSet<CLIENTE_SATISFACAO> CLIENTE_SATISFACAO { get; set; }
        public virtual DbSet<DESPESA_RECORRENTE> DESPESA_RECORRENTE { get; set; }
        public virtual DbSet<OSSB_SITUACAO_HISTORICO> OSSB_SITUACAO_HISTORICO { get; set; }
        public virtual DbSet<TIPO_CONTA> TIPO_CONTA { get; set; }
        public virtual DbSet<CONTA_BANCARIA> CONTA_BANCARIA { get; set; }
        public virtual DbSet<OSSB_MATERIAL> OSSB_MATERIAL { get; set; }
    
        public virtual int COPIAR_SERVICOS_OSSB(Nullable<int> from, Nullable<int> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COPIAR_SERVICOS_OSSB", fromParameter, toParameter);
        }
    }
}
