//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSSB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OSSB()
        {
            this.OSSB_COMUNICACAO = new HashSet<OSSB_COMUNICACAO>();
            this.OSSB_ESPECIALIDADE = new HashSet<OSSB_ESPECIALIDADE>();
            this.OSSB_SERVICO = new HashSet<OSSB_SERVICO>();
            this.OSSB_CHECK_LIST = new HashSet<OSSB_CHECK_LIST>();
            this.OSSB_ALBUM = new HashSet<OSSB_ALBUM>();
            this.OSSB_TECNICO = new HashSet<OSSB_TECNICO>();
            this.OSSB_VISTORIADOR = new HashSet<OSSB_VISTORIADOR>();
            this.FAT_FATURAMENTO = new HashSet<FAT_FATURAMENTO>();
            this.CAIXINHA_ITEM = new HashSet<CAIXINHA_ITEM>();
            this.CONTAS_RECEBER = new HashSet<CONTAS_RECEBER>();
            this.PAGAMENTO = new HashSet<PAGAMENTO>();
            this.OSSB_SITUACAO_HISTORICO = new HashSet<OSSB_SITUACAO_HISTORICO>();
            this.OSSB_MATERIAL = new HashSet<OSSB_MATERIAL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RESPONSAVEL { get; set; }
        public Nullable<int> SUPERVISOR { get; set; }
        public Nullable<int> CONTRATO { get; set; }
        public System.DateTime DATA_CADASTRO { get; set; }
        public int PROJETO { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public string OCORRENCIA { get; set; }
        public string PORTE { get; set; }
        public string AMBIENTE { get; set; }
        public string TIPO { get; set; }
        public string SITUACAO { get; set; }
        public Nullable<System.DateTime> EXECUCAO_INICIO { get; set; }
        public Nullable<System.DateTime> EXECUCAO_FIM { get; set; }
        public Nullable<System.DateTime> PREVISAO_INICIO { get; set; }
        public Nullable<System.DateTime> PREVISAO_FIM { get; set; }
        public Nullable<System.DateTime> EFETIVO_INICIO { get; set; }
        public Nullable<System.DateTime> EFETIVO_FIM { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> ORCAMENTISTA { get; set; }
        public Nullable<int> LOJA { get; set; }
        public Nullable<System.DateTime> QUANDO_PRECISA_ORCAMENTO { get; set; }
        public Nullable<System.DateTime> DATA_VISITA { get; set; }
        public Nullable<System.DateTime> DATA_FOLLOW_UP { get; set; }
        public string PRAZO_PAGAMENTO { get; set; }
        public string PRAZO_EXECUCAO { get; set; }
    
        public virtual CONTRATO CONTRATO1 { get; set; }
        public virtual PESSOA PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_COMUNICACAO> OSSB_COMUNICACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_ESPECIALIDADE> OSSB_ESPECIALIDADE { get; set; }
        public virtual PROJETO PROJETO1 { get; set; }
        public virtual PESSOA RESPONSAVEL1 { get; set; }
        public virtual PESSOA PESSOA2 { get; set; }
        public virtual PESSOA ORCAMENTISTA1 { get; set; }
        public virtual LOJA LOJA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_SERVICO> OSSB_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_CHECK_LIST> OSSB_CHECK_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_ALBUM> OSSB_ALBUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_TECNICO> OSSB_TECNICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_VISTORIADOR> OSSB_VISTORIADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_FATURAMENTO> FAT_FATURAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAIXINHA_ITEM> CAIXINHA_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTAS_RECEBER> CONTAS_RECEBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGAMENTO> PAGAMENTO { get; set; }
        public virtual CLIENTE_SATISFACAO CLIENTE_SATISFACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_SITUACAO_HISTORICO> OSSB_SITUACAO_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_MATERIAL> OSSB_MATERIAL { get; set; }
    }
}
