//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSSB_ALBUM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OSSB_ALBUM()
        {
            this.OSSB_IMAGEM = new HashSet<OSSB_IMAGEM>();
        }
    
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
        public int OSSB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSSB_IMAGEM> OSSB_IMAGEM { get; set; }
        public virtual OSSB OSSB1 { get; set; }
    }
}
