//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSSB_SITUACAO_HISTORICO
    {
        public int ID { get; set; }
        public int PESSOA { get; set; }
        public int OSSB { get; set; }
        public System.DateTime DATA_ALTERACAO { get; set; }
        public string DE { get; set; }
        public string PARA { get; set; }
    
        public virtual OSSB OSSB1 { get; set; }
        public virtual PESSOA PESSOA1 { get; set; }
    }
}
