//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGAMENTO_TERCEIRO
    {
        public int ID { get; set; }
        public System.DateTime DATA_PAGAMENTO { get; set; }
        public string OBSERVACAO { get; set; }
        public int OSSB_SERVICO { get; set; }
        public int TERCEIRO { get; set; }
        public decimal VALOR { get; set; }
        public int ANEXO { get; set; }
    
        public virtual PESSOA TERCEIRO1 { get; set; }
        public virtual OSSB_SERVICO OSSB_SERVICO1 { get; set; }
        public virtual OSSB_SERVICO_TERCEIRO OSSB_SERVICO_TERCEIRO { get; set; }
        public virtual ANEXO ANEXO1 { get; set; }
    }
}
