//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA_CLIENTE
    {
        public int ID { get; set; }
        public int CLIENTE { get; set; }
        public string FLG_LOJA { get; set; }
        public string FLG_CONTRATO { get; set; }
        public string COMO_CONHECEU { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
    }
}
