//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATEIO_PAGAMENTO_TERCEIRO
    {
        public int PAGAMENTO_TERCEIRO { get; set; }
        public int PROJETO { get; set; }
        public decimal VALOR { get; set; }
    
        public virtual PAGAMENTO_TERCEIRO PAGAMENTO_TERCEIRO1 { get; set; }
        public virtual PROJETO PROJETO1 { get; set; }
    }
}
