//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATIMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO
    {
        public int ID { get; set; }
        public int USUARIO { get; set; }
        public System.DateTime DATA_CRIACAO { get; set; }
        public string DESCRICAO { get; set; }
    }
}
